# Generated by Django 5.0.4 on 2024-04-29 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_post_logo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='logo',
            field=models.CharField(max_length=250, null=True),
        ),
    ]
